### ISSUE TITLE
[Bug Report]: allowMergeCommits is not working while merging

### ISSUE THREAD

**Issue by anikethsaha** [zeke/semantic-pull-requests#100]
hi !

I have setup this app for [docsify](https://github.com/docsifyjs/docsify). And Added the [following config](https://github.com/docsifyjs/docsify/blob/develop/.github/semantic.yml). 

```

titleAndCommits: true
allowMergeCommits: true
allowRevertCommits: true
anyCommit: true
```

It is working fine when pushing a commit with a custom commit message. But for merged commits,  it is failing.

https://github.com/docsifyjs/docsify/commit/60263578bab14081214b7e7ad8bf025bb7d803f5
https://github.com/docsifyjs/docsify/commit/4514cfb2af8bad0708fc7986181a93da888c1e94

I have set the `allowMergeCommits` option to true.

I wonder if there is leading whitespace for merge commits that might be passing negative for this check  🤔 

https://github.com/zeke/semantic-pull-requests/blob/b011f40b1679749628f51f74535fb19ccdbe72dd/lib/is-semantic-message.js#L5

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
