### ISSUE TITLE
rfc: consider not using console methods

### ISSUE THREAD

**Issue by cdaringe** [zeke/semantic-pull-requests#101]
# problem

https://github.com/zeke/semantic-pull-requests/blob/a1d743d558e012952f4d3ab395137487b32afe6e/lib/is-semantic-message.js#L14 usage bypasses my expressed intent when configuring probot logger

# discussion

if anything `log.debug(...)`, as this type of failure is _expected_, and thus we don't need to log expected behavior expect when we are tracing/debugging.

**Comment by zeke** [comment]
@cdaringe I'm open to changing this. Would you care to open a pull request making this change?

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
