### ISSUE TITLE
various APIs incompatible with latest probot/octokit

### ISSUE THREAD

**Issue by cdaringe** [zeke/semantic-pull-requests#102]
# problem

- `pullRequests.getCommits({ ..., number ])` needs to move to `pulls.listCommits({ ..., pull_number })`
- `repo.getContent` needs to move to `repo.getContents`

for latest probot/octorest compat

**Comment by zeke** [comment]
Thanks for catching this. Do you want to open a pull request to upgrade probot and octokit?

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
