### ISSUE TITLE
Custom types in PR aren't respected

### ISSUE THREAD

**Issue by ivanovaleksandar** [zeke/semantic-pull-requests#104]
I have the following `.github/semantic.yml` file, but the custom **types** are not being respected in the PR title:

```
titleOnly: true

types:
- major
- minor
- patch
- feat
- fix
- docs
- ci
- build
- test
```

Are the custom types only applicable to commits, but not PRs?

**Comment by zeke** [comment]
> Are the custom types only applicable to commits, but not PRs?

I'm not actually sure, as I didn't implement that feature and I don't use any custom types in my projects. You may have to jump into the code here to figure out how it's working. If PR titles are not being supported, I will happily accept a pull request that fixes that.

**Comment by ivanovaleksandar** [comment]
So after testing once again, I noticed that after merging `.github/semantic.yml` to master, then every next PR will have the custom types. By default, only the pre-defined ones work, which is a weird behavior.

**Comment by zeke** [comment]
Ah yes that's [expected behavior](https://probot.github.io/api/latest/classes/context.html) from Probot:

> For security reasons, configuration is only loaded from the repository's default branch, changes made in pull requests from different branches or forks are ignored.

Thanks for following up. 👍🏼

**Comment by ivanovaleksandar** [comment]
Thank for clearing this up! It is good to be aware that this is the expected behaviour for Probot.
