### ISSUE TITLE
Status not updating when PR title is changed

### ISSUE THREAD

**Issue by protyposis** [zeke/semantic-pull-requests#108]
Hi,

I am frequently running into the following situation:

 1. new PR is opened, neither title nor commits are semantic, error status is set (red)
 2. PR title changed to be semantic
 3. status is not updated and stays in error status

Expectation: status should update and change to success (green) when the PR title is updated

Is this a bug or am I missing something?

Thanks!

**Comment by zeke** [comment]
Yeah it's supposed to work this way but I wonder if something regressed recently? I think I saw this happen on a PR the other day. Do you have a public example somewhere?

**Comment by protyposis** [comment]
I was evaluating your bot in a private repo so unfortunately there's no public example, I could however reliably reproduce this in every PR.

**Comment by janpio** [comment]
Possibly related: https://github.com/zeke/semantic-pull-requests/issues/112

**Comment by protyposis** [comment]
Yep the public example posted above perfectly demonstrates the problem.

**Comment by janpio** [comment]
In https://github.com/zeke/semantic-pull-requests/issues/112#issuecomment-680884075 I showed that this also happen when you open the PR with a semantic PR title already - the bot is still unhappy, not only when the PR is only renamed to have a semantic title.

**Comment by maitrungduc1410** [comment]
I'm having this problem in my private repo

**Comment by zeke** [comment]
I need help! https://github.com/zeke/semantic-pull-requests/issues/150

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
