### ISSUE TITLE
PR titles are not evaluated

### ISSUE THREAD

**Issue by janpio** [zeke/semantic-pull-requests#112]
README says:

> By default, only the PR title OR at least one commit message needs to have semantic prefix.

I think that used to work, but changed recently back to only taking commit messages into account.

See this public example: https://github.com/prisma/prisma/pull/3437

Would be great if this requirement would be relaxed again - as we squash merge our PRs the PR title will be used as the commit title, so having a semantic PR title is perfectly enough for us.

**Comment by janpio** [comment]
This also happens when the PR is opened with a semantic message as title: https://github.com/prisma/prisma/pull/3440

**Comment by michaelaflores** [comment]
This is happening for me as well, albeit in a private repo -- it appears to only pass the check when a commit has a semantic title but not if only the PR title is semantic. Is this fixed by specifying this in the config or is the behavior just broken either way?

**Comment by michaelaflores** [comment]
Fwiw, adding `titleOnly: true` did correctly cause it to ignore commits. Relying on default behavior that can change between runs without our intervention is probably problematic anyways.

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
