### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by stefanbuck** [zeke/semantic-pull-requests#116]
There is one error message which gets cut off in the status check and I wonder if there is something we can do about it.

![Screenshot 2020-09-28 at 12 41 12](https://user-images.githubusercontent.com/1393946/94422844-fb1b1180-0187-11eb-81e2-50cc612c998c.png)

A few ideas:

1) Come up with a shorter version
2) Introduce error codes which allows us to document the error in more detail in the README of this repository. 
3) Add a comment with the error to the pull request. This comment should go away automatically if the issue has been addressed.

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
