### ISSUE TITLE
Allow to configure prefered merge method

### ISSUE THREAD

**Issue by jGleitz** [zeke/semantic-pull-requests#117]
Currently, with `titleAndCommits: true`, the check will report “ready to be squashed” if a PR title is semantic, even if all commits are semantic. This probably makes sense for people who prefer squashing over merging or rebasing.

I prefer rebasing over squashing, so for me, it would be much more useful to read “ready to be rebased” if all commits are semantic and the PR title is too. With the current behaviour, if the PR author wrote a semantic PR title, I still have to check all commit messages manually to see if I can rebase.

Proposal: Add a setting like `preferredMergeStrategy`. If it is set to `squash` (should be the default to keep the current behaviour), the check behaves as it does now. If it is set to `rebase` or `merge`, the check will evaluate the commit messages before it evaluates the title, i.e. display “ready to be merged or rebased” whenever all commits are semantic.

**Comment by stephenmathieson** [comment]
Are you asking about the messaging in the bot, or the label on the "merge button"? If you're asking about the button, I'm not sure this is possible. It's been awhile since I looked, but I don't believe GitHub has an API for changing this at the individual PR level.

**Comment by jGleitz** [comment]
My main concern is the messaging of the bot. Of the bot could also influence the button, that would be nice to have, of course. The message is more important to me, though.

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
