### ISSUE TITLE
Require a scope

### ISSUE THREAD

**Issue by wincent** [zeke/semantic-pull-requests#119]
In a monorepo, [we'd like to _require_ that a scope always be provided](https://github.com/liferay/liferay-frontend-projects/issues/125), to make it easier for us to do things like filter notifications.

However, it seems that the `scopes` configuration can only be used [to detect invalid scopes, not require a scope when none is provided](https://github.com/zeke/semantic-pull-requests/blob/a1d743d558e012952f4d3ab395137487b32afe6e/lib/is-semantic-message.js#L20).

So, just wanted to propose this as a feature request.

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
