### ISSUE TITLE
Is the bot down?

### ISSUE THREAD

**Issue by jaimesuncin-telus** [zeke/semantic-pull-requests#125]
I see that one commit to master failed to pass the tests https://github.com/zeke/semantic-pull-requests/actions/runs/516216438 and I experimented staled pull request due to the semantic pull request bot. So I wonder if there is a correlation between that.

**Comment by charlie632** [comment]
It is down for our repo too 😢

**Comment by hi-rustin** [comment]
t is down for our repo too 😢

**Comment by ismay** [comment]
It is down for our repo too 😢

**Comment by zeke** [comment]
Sorry folks. I merged a contribution yesterday that looked like CI was passing, but it wasn't actually being run.

I've [reverted that change](https://github.com/zeke/semantic-pull-requests/pull/128https://github.com/zeke/semantic-pull-requests/pull/128) and the bot should stabilize in a few minutes.

**Comment by zeke** [comment]
I made a change to the Actions workflow so it will run on PRs from forks: https://github.com/zeke/semantic-pull-requests/pull/129 -- thanks to @cenobitedk and @jaimesuncin-telus for the help.

@puppybits can you open a new PR to redo your work and make any needed changes to get tests passing?

**Comment by bodinsamuel** [comment]
thanks @zeke 🙏🏻

**Comment by SachinShekhar** [comment]
In my case, it's still in pending state: https://github.com/ServerlesslyStack/Serverlessly/pull/57

Is it possible to refresh it without pushing new commit? Some bot command or something?

**Comment by hi-rustin** [comment]
> In my case, it's still in pending state: [ServerlesslyStack/Serverlessly#57](https://github.com/ServerlesslyStack/Serverlessly/pull/57)
> 
> Is it possible to refresh it without pushing new commit? Some bot command or something?

Try to reedit your PR title.
