### ISSUE TITLE
enhance title check

### ISSUE THREAD

**Issue by qiwang97** [zeke/semantic-pull-requests#131]
when make a pr with semantic title , it checks and pass through.
But if i edit the title without changing code, it doesn't check again.

Please do something to make it work.

**Comment by smasala** [comment]
Yes, same issue. Doesn't trigger on title change. Tried setting the PR to draft and back again (didn't trigger it either). Only workaround was to push another commit

**Comment by smasala** [comment]
Closing and opening the PR again works.

**Comment by slaven3kopic** [comment]
Same here. Any news about this?

**Comment by zeke** [comment]
Sorry to hear it's not working. I'm not able to investigate right now but if you can open a PR with a failing test the reproduces the issue that would be very helpful.

**Comment by stefancplace** [comment]
I have the same problem ...

**Comment by hippiechick60** [comment]
Sent from Yahoo Mail on Android 
 
  On Mon, May 17, 2021 at 1:25 AM, Stefan ***@***.***> wrote:   


I have the same problem ...

**Comment by smasala** [comment]
@zeke as requested: https://github.com/zeke/semantic-pull-requests/pull/145 the PR shows that the check doesn't trigger again on title change.

Here is an example on another app and the required event: https://github.com/coleHafner/semantic-pr-title/blob/master/index.js#L15

**Comment by zeke** [comment]
I need help! https://github.com/zeke/semantic-pull-requests/issues/150

**Comment by smasala** [comment]
This can be marked as closed or?

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.

**Comment by tobiasbueschel** [comment]
Hi  @zeke - thanks for your work on this, I really like this `semantic-pull-requests` as it ties in well with [release-please](https://github.com/googleapis/release-please).

Unfortunately, I also still have the same issue => when the PR title wasn't semantic first, it doesn't check again after I fixed the PR title.

Hence, would be great if we could re-open this issue.

**Comment by zeke** [comment]
Thank for weighing in @tobiasbueschel. I reopened the issue. I don't have time at the moment to work on a fix for this but if you want to work on it I'd be happy to help you test and ship it.
