### ISSUE TITLE
Resource not accessible by integration for dependabot PRs

### ISSUE THREAD

**Issue by sk-** [zeke/semantic-pull-requests#134]
Yesterday we started getting the error: `Resource not accessible by integration` for all the PRs generated by dependabot

```
Run amannn/action-semantic-pull-request@v2.1.0
  with:
  env:
    GITHUB_TOKEN: ***
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
Error: Resource not accessible by integration
```

**Comment by zeke** [comment]
Hello. It looks like you're using amannn/action-semantic-pull-request -- that's a similar but unrelated project. I would suggest opening an issue at https://github.com/amannn/action-semantic-pull-request/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
