### ISSUE TITLE
Deploying as new app (for use in GHE), but not processing new PRs

### ISSUE THREAD

**Issue by ScottChapman** [zeke/semantic-pull-requests#138]
So, I've deployed this and given it what appears to be the right permissions and is listening to all PR events. I do see output that suggests that it is getting the event: 
```
 DEBUG probot: Webhook received
   event: {
     "event": "pull_request.opened",
     "id": "51a5a280-a39b-11eb-9015-c519e05faaec",
     "installation": 3433,
     "repository": "<myrepo>"
   }
```
But... I don't see anything actually get processed. I threw in some debugging into the handler, and it doesn;t seem like that is getting called.

What might I be missing?

**Comment by zeke** [comment]
Figured it out? Can you share any details on what resolved your issue?

**Comment by ScottChapman** [comment]
yea, I suspect that it wasn't properly using my app config. For example, I hadn'y set the `APP_ID` properly. It seems to be working now.

Any reason you didn't use the significantly more popular https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser ?

**Comment by zeke** [comment]
If there was a reason, I can no longer remember what it was. 🤔 

If you think that module has better support and is more actively maintained, and it passes tests on this project, I'd happily accept a pull request to use it.

**Comment by ScottChapman** [comment]
ha, yea.
Let em noodle on it and see if I can do a drop in replacement.

**Comment by ScottChapman** [comment]
@zeke - how do I run the tests exactly? When I run I get a lot of missing nocks.

**Comment by zeke** [comment]
`npm install and npm test` should do the trick. If you're still stuck, can open a new issue for this and ping me from there?

**Comment by ScottChapman** [comment]
Yea, that's what I was doing. let me open a new issue for it
