### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by ScottChapman** [zeke/semantic-pull-requests#139]
After doing an install, I run `npm run test` and get a bunch of errors like:
``` 
● handlePullRequestChange › sets `failure` status if PR has no semantic commits and no semantic title

    HttpError: request to https://api.github.com/repos/sally/project-x/statuses/abcdefg failed, reason: Nock: No match for request {
      "method": "POST",
      "url": "https://api.github.com/repos/sally/project-x/statuses/abcdefg",
      "headers": {
        "accept": [
          "application/vnd.github.v3+json"
        ],
        "user-agent": [
          "octokit/rest.js v15.9.4"
```

**Comment by zeke** [comment]
What version of Node.js are you running?

Please try a fresh checkout:

```
git clone https://github.com/zeke/semantic-pull-requests
cd semantic-pull-requests
npm install
npm test
```

**Comment by zeke** [comment]
Any luck, @ScottChapman ?

**Comment by ScottChapman** [comment]
I have, but with a different [project](https://github.com/z0al/commitlint-bot); I liked what it did a bit better as it maintained a comment with details. We've customized it for our use so I think we are all set.

**Comment by zeke** [comment]
Just checked out https://github.com/z0al/commitlint-bot -- It is archived and links to this project!? 🙈 

In any case, glad you got something going that works for you 👍🏼
