### ISSUE TITLE
Loading semantic.yml seems to be broken

### ISSUE THREAD

**Issue by sapkra** [zeke/semantic-pull-requests#141]
For me it seems like that loading the config file is broken somehow. Several users are reporting that their options are not working. Maybe the root of the problem is that `probot-config` is deprecated and is now part of the probot core.

@zeke Do you have any plans to refactor it?

Before:
```javascript
const getConfig = require('probot-config')
const userConfig = await getConfig(context, 'semantic.yml', {})
```

After:
```javascript
const userConfig = await context.config('semantic.yml')
```

**Comment by zeke** [comment]
@sapkra thanks for the ping, and sorry it's not working for you. Would you be willing to open a pull request to update this?

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
