### ISSUE TITLE
Empty space prefixing PR title should make the pr title invalid

### ISSUE THREAD

**Issue by skimi** [zeke/semantic-pull-requests#149]
I've just stumbled onto this one:

- Have a PR with a valid conventional title but prefixed with a space
```
  fix: my broken feature
```
- The bot will show `ready to be squashed`

This is an issue because the `conventional-commits` lib won't recognise the commit. So, we thought the commit was correct but then the changelog and version numbering did not follow

**Comment by zeke** [comment]
I need help! https://github.com/zeke/semantic-pull-requests/issues/150

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
