### ISSUE TITLE
Github IP allow list

### ISSUE THREAD

**Issue by joshuasimon-taulia** [zeke/semantic-pull-requests#152]
When I enable **IP allow list** in https://github.com/organizations/${MY_ORG}/settings/security, semantic-pull-requests stops showing up as a check in my PRs. Github provides an option to **Enable IP allow list configuration for installed GitHub Apps**, but when I enable it, I see "You have no installed GitHub Apps that define their own IP allow list entries".

Would you be able to add the egress ips of the app to the upstream github app?
"Integrators can set an IP allow list for a GitHub App by adding individual IP addresses or address ranges for the hosted service. If an enterprise account or organization has enabled IP allow lists and chosen to allow installed GitHub Apps to configure allowed IPs, then the IP addresses provided for a GitHub App will be inherited by the customers allow lists."
Or at least paste the egress ips into this repo's README?

**Comment by zeke** [comment]
Hi @joshuasimon-taulia -- that's a new one for me. This app is hosted on Heroku, so the IP changes often. Daily at the very least. Maybe the entire range of Heroku IPs could be whitelisted somehow? 🤔

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
