### ISSUE TITLE
Feature request: support for fixup! (git commit --fixup) commits

### ISSUE THREAD

**Issue by bnevis-i** [zeke/semantic-pull-requests#159]
I think it would be a nice feature if fixup commits (created by git commit --fixup) didn't throw off the regexp parser.

The intended workflow is submitting additional commits to a pull request in responds to pull request feedback.

It is easier to run git commit --fixup than it is to put new commits on top and duplicate the commit messages such that they are semantic PR compliant.

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
