### ISSUE TITLE
Is semantic-pull-requests service down?

### ISSUE THREAD

**Issue by ValentinBouffard** [zeke/semantic-pull-requests#162]
Hello,

Since this morning (October 12th), all of our PR's are stuck waiting for the Semantic Pull Request status to be reported.

I've tried opening a new PR today and the same thing happens. We are using the github app: https://probot.github.io/apps/semantic-pull-requests/

Is it possible the service is down? How can we get to the bottom of this? We can't seem to find any incidents page for your service.

Thanks

<div><img src="https://media4.giphy.com/media/Nm8ZPAGOwZUQM/giphy.gif?cid=5a38a5a2ghsj3izsnfo0xojpk4mfivxhvw4fso7c0yhn19ug&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:284px;width:300px"/><br/>via <a href="https://giphy.com/gifs/reaction-Nm8ZPAGOwZUQM">GIPHY</a></div>

**Comment by josh-zozonz** [comment]
Down for us too

**Comment by zeke** [comment]
Oh noes!

GitHub has apparently shut down all the Probot apps it was hosting, including this one. Thank you @hiimbex for the heads up on Twitter: https://twitter.com/hiimbexo/status/1448090099758010376

I am a former GitHub employee. I didn't receive any notification that this was going to happen, but I believe I am still the owner of the GitHub App, so I should be able to get it deployed elsewhere and configured to point to a different domain. I'll keep this thread updated as that progresses. 🤞🏼

**Comment by tcbyrd** [comment]
Should be back up.
