### ISSUE TITLE
Is it a issue? When there is no space after colon, PR is invalid

### ISSUE THREAD

**Issue by elfisworking** [zeke/semantic-pull-requests#166]
When there is no space after the colon, it is recognized as invalid PR.
for example:
PR tille
```
fix:solve function load error
```
semantic-pull-requests returns false

**Comment by zeke** [comment]
Yeah the space is required. From the [Conventional Commits spec](https://www.conventionalcommits.org/en/v1.0.0/#specification):

> Commits MUST be prefixed with a type, which consists of a noun, feat, fix, etc., followed by the OPTIONAL scope, OPTIONAL !, and REQUIRED terminal colon **and space**.

**Comment by elfisworking** [comment]
thanks!
