### ISSUE TITLE
Semantic bot not working, no semantic entry in checks

### ISSUE THREAD

**Issue by riyaz** [zeke/semantic-pull-requests#176]
It used to work till yesterday but from today morning (IST) I don't see Semantic PR under checks, I tried reinstalling the app but it doesn't help. Its private in private repo.

**Comment by zeke** [comment]
This should be fixed now.

It was a Node.js upgrade that passed CI but failed in production: https://github.com/zeke/semantic-pull-requests/pull/177

**Comment by riyaz** [comment]
Working now. Thanks.
