### ISSUE TITLE
feature: support optional scope in type

### ISSUE THREAD

**Issue by jbergstroem** [zeke/semantic-pull-requests#180]
Types supports an optional scope: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-scope

My use case is for the bot to be ok with the renovatebot default configuration (`chore(deps):`).

**Comment by zeke** [comment]
I thought scopes were already supported? But maybe not. I would happily support a PR for this if you have time to work on it and add tests.

**Comment by jbergstroem** [comment]
> I thought scopes were already supported? But maybe not.

Me too! This PR title fails for me: `chore(deps): all non-major dependencies`:

<img width="446" alt="Screen Shot 2022-03-21 at 1 14 34 PM" src="https://user-images.githubusercontent.com/176984/159303996-9173019e-aa09-43ea-bbcb-2e5f0b544001.png">


> I would happily support a PR for this if you have time to work on it and add tests.

Sounds good to me.

**Comment by jbergstroem** [comment]
Edit: I'm stupid - typo in scope list..
