### ISSUE TITLE
App stops working in aws/aws-sdk-js-v3

### ISSUE THREAD

**Issue by AllanZhengYP** [zeke/semantic-pull-requests#187]
The semantic PR App has been very helpful for us. Recently we notice the App stops working on our repo https://github.com/aws/aws-sdk-js-v3. 

You can see it ran on some of our old pending PRs like this: ✅ https://github.com/aws/aws-sdk-js-v3/pull/3430, but not for the latest PRs, like: 🔴 https://github.com/aws/aws-sdk-js-v3/pull/3583

Do you have any idea the cause it? Are we hitting any limit?

**Comment by zeke** [comment]
Hi folks. I hope most of you have moved on by now and found better ways to do semantic checks on your PRs.

For those who haven't, it's time to start looking. Effective today, I will no longer be maintaining this service.

For details on why it reached a breaking point, see this PR: https://github.com/zeke/semantic-pull-requests/pull/189

Thanks for your understanding, and happy hacking!
