### ISSUE TITLE
Status check stuck in "Expected — Waiting for status to be reported" state

### ISSUE THREAD

**Issue by DeepaKulkarniNews** [zeke/semantic-pull-requests#195]
Hi,

I tried to close and reopen the PR multiple times and have also ensured that the PR and commit messages adhere to right semantics, but the Semantic check is stuck at Expected — Waiting for status to be reported state. Is there an outage?

**Comment by travi** [comment]
from [the readme](https://github.com/zeke/semantic-pull-requests#readme):

> ⚠️ THIS SERVICE IS NO LONGER MAINTAINED ⚠️
