### ISSUE TITLE
Add a commitsAny to validate any commit is semantic, and not the title

### ISSUE THREAD

**Issue by grrowl** [zeke/semantic-pull-requests#41]
Our sematic-release bot does not see the PR title, but we only want to validate _any_ commit is semantic.

Suggestion: Add a `commitsAny: true` to enforce this behaviour; alternatively, a `ignoreTitle: true` option so we can avoid specifying `commitsOnly: true`

**Comment by grrowl** [comment]
yes that is correct. matching the default behaviour, we'd like at least one semantic commit to be a pass, without checking the title.

**Comment by zeke** [comment]
I'd accept a pull request adding this behavior.

**Comment by rarneson** [comment]
Should this issue be closed?

**Comment by zeke** [comment]
Yep. Thanks @rameson 👍
