### ISSUE TITLE
Optionally allow failing the check

### ISSUE THREAD

**Issue by Buzzertech** [zeke/semantic-pull-requests#54]
### Context
When validation fails, it should be optionally allowed (via a config param) to fail the check instead of leaving it in a `pending` state.

### Motivation
Sometimes, we'd like to have things a little stricter and disable merge entirely if the validation fails instead of suggesting the user to fix the PR title or commit message name whilst still allowing the PR to be merged

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
