### ISSUE TITLE
titleOnly option is being ignored?

### ISSUE THREAD

**Issue by coleHafner** [zeke/semantic-pull-requests#70]
I have a PR with an invalid PR title and the `titleOnly: true` option in my `.github/semantic.yml` file. I still get the status "ready to be merged or rebased". It doesn't seem to matter what I do, this will always be the status. The PR does have many commits that meet the conventional commit standard, but those should be ignored per the `titleOnly` option, right?

![Screen Shot 2019-09-15 at 2 20 39 PM](https://user-images.githubusercontent.com/380835/64927775-4ef8c980-d7c4-11e9-9b69-9d721097b783.png)

Config file:

![Screen Shot 2019-09-15 at 2 24 10 PM](https://user-images.githubusercontent.com/380835/64927798-8ebfb100-d7c4-11e9-9a2b-d4ce0ed420c8.png)

This repo is a private one within an org, so I'm not sure if that has anything to do with it. I know it has been an issue with other apps I've tried.

**Comment by coleHafner** [comment]
This is still an issue, but I found a different solution. I'm closing it for now.

**Comment by zeke** [comment]
Hi. What was your different solution?

**Comment by zeke** [comment]
Re-opening this so we can fix it, regardless of the workaround you found.

**Comment by coleHafner** [comment]
@zeke Yours is the third app I've tried to find a solution, but none of them seem to work as advertised. I suspect it has something to do with our private repo within our organization.

I created [an app](https://github.com/coleHafner/pr-title-linter) that meets my requirements (mostly out of curiosity of how to create a GitHub App). It seems to be working fine for our team.

**Comment by zeke** [comment]
Thanks for the info.

`titleOnly` support was added in https://github.com/probot/semantic-pull-requests/pull/30. Hey @guyfedwards are you using this feature successfully?

**Comment by guyfedwards** [comment]
Yep this works perfectly for our usecase!

**Comment by zeke** [comment]
@guyfedwards is your repo public or private?

**Comment by guyfedwards** [comment]
Open source https://github.com/guyfedwards/emojo. Not much activity on it for a while but you can see some failed PRs

**Comment by mrchief** [comment]
Came here to report the same thing. Can someone pin the solution/workaround?

**Comment by jayithiel** [comment]
`titleOnly` is being ignored for me as well. It also checks the commit if there is only 1 commit

**Comment by don-hover** [comment]
@zeke 
Please see:
https://github.com/zeke/semantic-pull-requests/pull/105#issuecomment-785975869

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
