### ISSUE TITLE
Exclamation (breaking change) is not recognized

### ISSUE THREAD

**Issue by binarylogic** [zeke/semantic-pull-requests#73]
PR titles following the `!` BREAKING CHANGE syntax are not recognized as valid. For example, we have a PR title like so:

```
fix(config)!: ...
```

This does not pass validation (the PR check remains pending) even though it is valid according to the spec:

> BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope

The actual PR being referenced is https://github.com/timberio/vector/pull/1033.

**Comment by zeke** [comment]
Thanks for opening this issue, and sorry for the delay getting back to you.

This app uses the [`parse-commit-message`](https://github.com/tunnckoCoreLabs/parse-commit-message) npm package to validate commits. I think the `!` support needs to be added there.

cc @tunnckoCore (author of  `parse-commit-message`) does that sound right?

**Comment by tunnckoCore** [comment]
Uh, yea, I forgot about that. I can update probably these days or at the weekend.

**Comment by binarylogic** [comment]
Thanks @tunnckoCore, that would be helpful.

**Comment by tunnckoCore** [comment]
Oh, damn me, sorry... how time flies. I'm on it this night! :)
Expect release tomorrow, maximum 24-36h.

**Comment by tunnckoCore** [comment]
Okay, i've done a lot of things and wanted to release v4 release. But will go with the simple one (with just adding the `!` to the regex) and a patch version to resolve these issues.

**Comment by tunnckoCore** [comment]
@zeke please use `4.0.0-alpha.12` / the `next` dist-tag. For now.

**Comment by zeke** [comment]
I opened PR https://github.com/zeke/semantic-pull-requests/pull/75 using `4.0.0-alpha.12` but some tests are failing now: https://travis-ci.org/zeke/semantic-pull-requests/builds/616072483

**Comment by zeke** [comment]
This should be auto-deployed momentarily. @binarylogic let us know how it goes!

**Comment by binarylogic** [comment]
Thank you!

**Comment by binarylogic** [comment]
@zeke we're still seeing this problem :( Is there anything we need to do to update? For example:

https://github.com/timberio/vector/pull/1404

**Comment by tunnckoCore** [comment]
> @zeke we're still seeing this problem :( Is there anything we need to do to update? For example:
> 
> [timberio/vector#1404](https://github.com/timberio/vector/pull/1404)

probably because the space in scope? try that, if not... I can't help now.

**Comment by zeke** [comment]
Looks like the check was green by the time the PR was merged:

<img width="646" alt="Screen Shot 2020-01-07 at 2 46 17 PM" src="https://user-images.githubusercontent.com/2289/71935764-81a44480-315c-11ea-8d50-94a70a89918a.png">
