### ISSUE TITLE
Support gitmoji as valid semantic prefix

### ISSUE THREAD

**Issue by madmath03** [zeke/semantic-pull-requests#74]
Just a suggestion, but would it be possible to support [Gitmoji](https://gitmoji.carloscuesta.me/) as a valid semantic prefix ?

For instance, if I have a commit with message "_:sparkles: Bla bla bla_"  the :sparkles: (`:sparkles:`) might be enough to consider the commit to be about a new feature.
Same goes with :bug: `:bug:`, :zap: `:zap:`, :pencil: `:pencil:`, :construction_worker: `:construction_worker:`, etc...

What do you think ?

**Comment by zeke** [comment]
Hi @madmath03. That sounds fun. You can enable this in your project by specifying a custom list of `types`: https://github.com/zeke/semantic-pull-requests#configuration

**Comment by madmath03** [comment]
Hi @zeke,

I was thinking about something a little more complex, like being able to retrieve [Gitmoji's emoji config file](https://github.com/carloscuesta/gitmoji/blob/master/src/data/gitmojis.json) in this app, but that would probably be better suited in a different app.

Anyway, thanks a lot for your help.
