### ISSUE TITLE
Status check stuck in pending status

### ISSUE THREAD

**Issue by michaelsbradleyjr** [zeke/semantic-pull-requests#76]
Yesterday I enabled this status check for [my team's repo](https://github.com/embark-framework/embark/blob/master/.github/semantic.yml). I rebased a couple of PRs and got passing checks for those with conventional commits.

However, the status check got stuck in the *Pending* state on a [PR](https://github.com/embark-framework/embark/pull/2057) that I expected to simply fail the check — it's an open PR that's being reworked and has various WIP commits, some simply with a commit message of `.`. I don't expect there is anything to be done about it, and the PR is going to be closed and replaced in any case, but I thought it might be helpful to point it out as potentially being a bug in Semantic Pull Requests.

**Comment by michaelsbradleyjr** [comment]
Nevermind, I saw the yellow dot and because I'm so used to associating that with not-done-yet CI builds that I didn't read the message to the right of the dot:

> Pending — make sure every commit is semantic 

Then I re-read the README and saw it's the expected behavior.

I'll close this issue now; but I wonder if it might be better to use a red x-mark to signify the check didn't pass rather then using a yellow dot.

**Comment by zeke** [comment]
Yeah this just happened to @justinBeckwith the other day too: https://github.com/JustinBeckwith/linkinator/issues/122#issuecomment-557186829

I would be open to changing this behavior, as it appears to be confusing people!
