### ISSUE TITLE
Add configuration options based on 'commitlint' rules

### ISSUE THREAD

**Issue by rfgamaral** [zeke/semantic-pull-requests#80]
I usually configure my projects with `commitlint` and `husky` to lint the commit messages before they are pushed to the repository and personally I use `@commitlint/config-conventional` rules.

It would be nice if we could configure `semantic-pull-requests` with the same rules as `commitlint`. For instance, if I have a PR title like `chore: Title subject`, this is invalid with my `commitlint` configuration above (everything should be lower case) but `semantic-pull-requests` won't care and say it's fine.

The `commitlint` reference rules can be seen here: https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md

I understand that implementing all these options could be a big task so maybe we could just start off with the simple and easier rules like casing, for instance.

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
