### ISSUE TITLE
Scopes aren't being respected

### ISSUE THREAD

**Issue by joemckie** [zeke/semantic-pull-requests#82]
The plugin doesn't seem to be blocking incorrect scopes. The project is in a monorepo so would like to limit the scopes to the packages available 😄

Here is my config:

```
titleOnly: true
allowMergeCommits: false
scopes:
  - core-repo
  - admin-frontend
  - api
  - constants
  - logger
  - mailer
  - splash-page
```

And this is the output:

<img width="766" alt="Screenshot 2020-02-16 at 16 56 05" src="https://user-images.githubusercontent.com/4980618/74608943-4727b300-50dd-11ea-949b-5239c68b0fea.png">

<img width="759" alt="Screenshot 2020-02-16 at 16 56 10" src="https://user-images.githubusercontent.com/4980618/74608945-48f17680-50dd-11ea-84c6-cdd778453f85.png">

Only squash commits are allowed in the repository, if that makes a difference.

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
