### ISSUE TITLE
commitsOnly being ignored

### ISSUE THREAD

**Issue by baconjulie** [zeke/semantic-pull-requests#88]
Similar issue to #70 when setting `commitsOnly: true` in a `.github/semantic.yml` the check incorrectly passes so long as the PR title is semantic. This is in a private repo.

File change:

![Screen Shot 2020-04-20 at 11 20 13 AM](https://user-images.githubusercontent.com/5865863/79768538-ee50e280-82f8-11ea-9f07-2bfd4b031335.png)

Semantic title, non-semantic commit
![Screen Shot 2020-04-20 at 11 19 13 AM](https://user-images.githubusercontent.com/5865863/79768473-d711f500-82f8-11ea-86ea-d275fa7db617.png)

Passes check when it should not
![Screen Shot 2020-04-20 at 11 18 57 AM](https://user-images.githubusercontent.com/5865863/79768475-d7aa8b80-82f8-11ea-9417-7978c35bfe4f.png)

**Comment by sapkra** [comment]
@baconjulie Were you able to find a solution for it? To me it seems like that the script is unable to load the `semantic.yml`. I have the same problem with `titleAndCommits` and several other people are reporting the same issue with different options.

**Comment by zeke** [comment]
Hi folks. Apologies for the long silence.

I do not currently have the time to make the fix myself, but if this is indeed a regression I will happily review/ship/deploy a pull request that addresses the issue. If anyone ends up opening a PR, please ping me @zeke directly so the notification doesn't fall through the cracks of my many hundreds of repos 🙀 

Thanks for understanding!

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
