### ISSUE TITLE
Only apply to some subpaths of the repository

### ISSUE THREAD

**Issue by felixfbecker** [zeke/semantic-pull-requests#89]
In a monorepo, I want to enforce the semantic convention for only part of the repository (specific directories).
Would it be possible to have an option for that in the YAML?

**Comment by zeke** [comment]
I can see how that would be useful, but it seems like it could add a lot of complexity to this app.

I've been thinking it would be good to rewrite this app as a GitHub Action. Your issue prompted me to open a new issue about that: https://github.com/zeke/semantic-pull-requests/issues/90

**Comment by felixfbecker** [comment]
Often GitHub apps allow you to configure them through a YAML file that's checked into the repo, e.g. https://github.com/wei/pull
I don't have a good idea of what this entails, but would it really add that much complexity? Without this it makes the app not easy to adapt in a monorepo :/

**Comment by zeke** [comment]
The app currently looks at commits, and commit messages. It doesn't analyze file changes. So yes, without digging too deeply, I think it would be a nontrivial change to make. That said, if you are eager to see this supported, I would welcome a pull request that implements this, with tests, and without breaking any existing functionality.

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
