### ISSUE TITLE
Upgrade conventional-commit-types to 3.0.0

### ISSUE THREAD

**Issue by felipecassiors** [zeke/semantic-pull-requests#93]
It removed `improvement` https://github.com/commitizen/conventional-commit-types/releases/tag/v3.0.0

**Comment by zeke** [comment]
I wonder why @dependabot didn't open a PR for that 🤔

**Comment by felipecassiors** [comment]
Yeah, I was wondering that too 🤔.

**Comment by zeke** [comment]
I would accept a PR for this!
