### ISSUE TITLE
publish as library

### ISSUE THREAD

**Issue by cdaringe** [zeke/semantic-pull-requests#99]
# problem

- i want to plug this into my probot server, but this isn't published to npm: https://www.npmjs.com/search?q=semantic-pull-requests

# discussion

- can we export the handler/handlers,
- publish as a lib

thanks for the consideration

**Comment by zeke** [comment]
I'm open to this 👍

**Comment by zeke** [comment]
This issue is old and inactive so I'm going to close it. If anyone is still affected by this, let me know and I'll re-open it.
